version: 2.0

jobs:
  unit-test:
    docker:
      - image: circleci/node:10.12-stretch
    steps:
      - checkout
      - run:
          name: Install
          command: |
            npm install
      - run:
          name: Test
          command: |
            npm test
  coverage:
    docker:
      - image: circleci/node:10.12-stretch
    steps:
      - checkout
      - run:
          name: Install
          command: |
            npm install
      - run:
          name: Test & Coveralls
          command: |
            npm run coverage && cat coverage/lcov.info | coveralls

workflows:
  version: 2
  build:
    jobs:
      - unit-test
      - coverage
